title: DeFraG's thoughts on web
markdown: kramdown
theme: minima
description: >- # this means to ignore newlines until "baseurl:"
  DeFraG's tech blog 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://defrag.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: defrag2
github_username:  defrag
linkedin_username: dabrowski-michal
plugins:
  - jekyll-feed
google_analytics: G-ZZN15C8WZC
